spring.application.name=kedusoft


#DB
#spring.datasource.url=jdbc:mariadb://kedusoft.co.kr:3306/kedusoft
#spring.datasource.username=kedusoft
#spring.datasource.password=ZPEBTHVMXM0909
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# logback 설정 파일이 위치하는 곳
logging.config=classpath:logback-prod.xml
logging.charset.console=UTF-8
logging.level.root=info
spring.output.ansi.enabled=ALWAYS

#sql-log를 위해
spring.datasource.hikari.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#spring.datasource.hikari.driver-class-name=org.mariadb.jdbc.Driver

spring.datasource.hikari.jdbc-url=jdbc:log4jdbc:mariadb://localhost:3306/kedusoft?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.hikari.username=kedusoft
spring.datasource.hikari.password=ZPEBTHVMXM0909

#유휴(데이터를 전송하지 않는 상태) 연결의 최대 유지 시간(이시간이지나면 제거됨) 30초 (ms)
spring.datasource.hikari.idle-timeout:30000



#mapper
#mybatis.mapper-locations=mapper/*.xml